### ISSUE TITLE
What am i doing wrong?

### ISSUE THREAD

**Issue by Barmem** [patrickhener/goshs#25]
![IMG_20220411_155027.jpg](https://user-images.githubusercontent.com/70278808/162713407-c5e9f381-e7b1-4688-87bb-a6cb3251a2ec.jpg)

**Comment by patrickhener** [comment]
Well a little more information would be useful but judging from your screenshot you are running on android. So first question is, how did you build it? Or are you just trying to run the linux executable. Because this will not work I assume. Also maybe the executable is not really executable. So quick fix might be a `chmod +x goshs`. But at this point I am just guessing.

**Comment by Barmem** [comment]
So, im using termux, i tried installing it with go, and it seems like it installed but when i try `goshs` it says command not found. I tried running arm64 executable from releases and it gives output from screenshot above

**Comment by patrickhener** [comment]
So I assume (without testing myself) that arm64 will then not work on android. I guess your best bet will be building on device and running it then. For go it is important to have set a gopath. So I guess the fact you cannot find goshs after building means that the path the binaries is compiled to is not in your devices path to begin with. If you have `find` on cli I would try locating the file with it. Maybe this helps.

**Comment by Barmem** [comment]
Seems like path was the issue, thanks

**Comment by patrickhener** [comment]
Glad I could help
